# load default page objects, widgets, and locators
from m_osr_1_1_0 import *


# load page object overrides


# load widget overrides


# load page object locator overrides
from po_login import LoginPage1_Locators_Base_1 as LoginPage_Locators
from po_tools_status_approved_page import ContribtoolToolsStatusApprovedPage as ToolsStatusApprovedPage
from po_tools_status_approved_page import ContribtoolToolsStatusApprovedAdminPage as ToolsStatusApprovedAdminPage
from po_tools_status_created_page import ContribtoolToolsStatusCreatedPage as ToolsStatusCreatedPage
from po_tools_status_created_page import ContribtoolToolsStatusCreatedAdminPage as ToolsStatusCreatedAdminPage
from po_tools_status_installed_page import ContribtoolToolsStatusInstalledPage as ToolsStatusInstalledPage
from po_tools_status_installed_page import ContribtoolToolsStatusInstalledAdminPage as ToolsStatusInstalledAdminPage
from po_tools_status_published_page import ContribtoolToolsStatusPublishedPage as ToolsStatusPublishedPage
from po_tools_status_published_page import ContribtoolToolsStatusPublishedAdminPage as  ToolsStatusPublishedAdminPage
from po_tools_status_registered_page import ContribtoolToolsStatusRegisteredPage as ToolsStatusRegisteredPage
from po_tools_status_registered_page import ContribtoolToolsStatusRegisteredAdminPage as ToolsStatusRegisteredAdminPage
from po_tools_status_uploaded_page import ContribtoolToolsStatusUploadedPage as ToolsStatusUploadedPage
from po_tools_status_uploaded_page import ContribtoolToolsStatusUploadedPage as ToolsStatusUploadedAdminPage


# load widget locator overrides
from widgets.header import Header3_Locators_Base_3 as Header_Locators
from widgets.login_base import Login_Locators_Base_4 as Login_Locators
from widgets.members_change_password_form import MembersChangePasswordForm_Locators_Base_2 as MembersChangePasswordForm_Locators
from widgets.ticket_save import TicketSave_Locators_Base as TicketSave_Locators
