# represents hubs updated around November 2013

# load default page object, widgets, and locators
from m_osr_1_1_5 import *
#from m_overrides_group_wiki_editors import *


# load page object overrides
from po_admin_base_page import AdminBasePage
from po_admin_database_backup_page import AdminDatabaseBackupPage
from po_admin_database_list_page import AdminDatabaseListPage
from po_admin_database_table_list_page import AdminDatabaseTableListPage
from po_admin_database_table_manage_page import AdminDatabaseTableManagePage


# load widget overrides
from widgets.admin_database_backup import AdminDatabaseBackup1 as AdminDatabaseBackup
from widgets.admin_database_list import AdminDatabaseList1 as AdminDatabaseList
from widgets.admin_database_list_item import AdminDatabaseListItem1 as AdminDatabaseListItem
from widgets.admin_database_table_list import AdminDatabaseTableList1 as AdminDatabaseTableList
from widgets.admin_database_table_list_item import AdminDatabaseTableListItem1 as AdminDatabaseTableListItem
from widgets.admin_database_table_manage_batch_update import AdminDatabaseTableManageBatchUpdate1 as AdminDatabaseTableManageBatchUpdate
from widgets.admin_header import AdminHeader1 as AdminHeader
from widgets.admin_login import AdminLogin1 as AdminLogin
from widgets.admin_menu import AdminMenu1 as AdminMenu
from widgets.groups_wiki_new_form import GroupsWikiNewForm3 as GroupsWikiNewForm
from widgets.groups_wiki_edit_form import GroupsWikiEditForm3 as GroupsWikiEditForm
from widgets.header import Header2 as Header
from widgets.tags_browse_results_row import TagsBrowseResultsRow2 as TagsBrowseResultsRow
from widgets.upload3 import Upload3
from widgets.upload_list_row import UploadListRow


# load page object locator overrides
from po_admin_base_page import AdminBasePage_Locators_Base as AdminBasePage_Locators
from po_admin_database_backup_page import AdminDatabaseBackupPage_Locators_Base as AdminDatabaseBackupPage_Locators
from po_admin_database_list_page import AdminDatabaseListPage_Locators_Base as AdminDatabaseListPage_Locators
from po_admin_database_table_list_page import AdminDatabaseTableListPage_Locators_Base as AdminDatabaseTableListPage_Locators
from po_admin_database_table_manage_page import AdminDatabaseTableManagePage_Locators_Base as AdminDatabaseTableManagePage_Locators
from po_generic_page import GenericPage_Locators_Base_1 as GenericPage_Locators
from po_login import LoginPage1_Locators_Base_3 as LoginPage_Locators
from po_wishlistsearch import WishlistSearchPage_Locators_Base_2 as WishlistSearchPage_Locators


# load widget locator overrides
from widgets.admin_database_backup import AdminDatabaseBackup1_Locators_Base_1 as AdminDatabaseBackup_Locators
from widgets.admin_database_list import AdminDatabaseList1_Locators_Base_1 as AdminDatabaseList_Locators
from widgets.admin_database_list_item import AdminDatabaseListItem1_Locators_Base_1 as AdminDatabaseListItem_Locators
from widgets.admin_database_table_list import AdminDatabaseTableList1_Locators_Base_1 as AdminDatabaseTableList_Locators
from widgets.admin_database_table_list_item import AdminDatabaseTableListItem1_Locators_Base_1 as AdminDatabaseTableListItem_Locators
from widgets.admin_database_table_manage_batch_update import AdminDatabaseTableManageBatchUpdate1_Locators_Base_1 as AdminDatabaseTableManageBatchUpdate_Locators
from widgets.admin_header import AdminHeader1_Locators_Base_1 as AdminHeader_Locators
from widgets.admin_login import AdminLogin1_Locators_Base_2 as AdminLogin_Locators
from widgets.admin_menu import AdminMenu1_Locators_Base_1 as AdminMenu_Locators
from widgets.groups import Groups2_Locators_Base_2 as Groups_Locators
from widgets.groups_wiki_new_form import GroupsWikiNewForm3_Locators_Base as GroupsWikiNewForm_Locators
from widgets.groups_wiki_edit_form import GroupsWikiEditForm3_Locators_Base as GroupsWikiEditForm_Locators
from widgets.header import Header2_Locators_Base_2 as Header_Locators
from widgets.login_base import Login_Locators_Base_3 as Login_Locators
from widgets.tags import Tags_Locators_Base_2 as Tags_Locators
from widgets.tags_browse_results_row import TagsBrowseResultsRow2_Locators_Base_1 as TagsBrowseResultsRow_Locators
from widgets.ticket_comment import TicketComment_Locators_Base_3 as TicketComment_Locators
from widgets.ticket_comment_form import TicketCommentForm_Locators_Base_2 as TicketCommentForm_Locators
from widgets.upload3 import Upload3_Locators_Base as Upload3_Locators
from widgets.upload_list_row import UploadListRow_Locators_Base as UploadListRow_Locators
from widgets.wishlist_search_form import WishlistSearchForm_Locators_Base_2 as WishlistSearchForm_Locators
